FROM openjdk:17-jdk-alpine

# Establecer directorio de trabajo
WORKDIR /app

# Copiar el archivo .jar
COPY target/dockerized.postgresql-0.0.1-SNAPSHOT.jar java-app.jar

# Copiar el keystore a /app/resources dentro del contenedor
COPY src/main/resources/keystore.p12 /app/keystore.p12

ENTRYPOINT ["java", "-jar", "java-app.jar"]
